data = [
    {"name": "Cristiano", "second_name": "Ronaldo", "follower_count": 630, "description": "footballer", "country": "Portugal"},
    {"name": "Lionel", "second_name": "Messi", "follower_count": 500, "description": "footballer", "country": "Argentina"},
    {"name": "Selena", "second_name": "Gomez", "follower_count": 430, "description": "singer actress", "country": "United States"},
    {"name": "Kylie", "second_name": "Jenner", "follower_count": 400, "description": "media personality", "country": "United States"},
    {"name": "Dwayne", "second_name": "Johnson", "follower_count": 395, "description": "actor wrestler", "country": "United States"},
    {"name": "Ariana", "second_name": "Grande", "follower_count": 380, "description": "pop singer", "country": "United States"},
    {"name": "Kim", "second_name": "Kardashian", "follower_count": 365, "description": "media personality", "country": "United States"},
    {"name": "Beyonce", "second_name": "Knowles", "follower_count": 315, "description": "singer performer", "country": "United States"},
    {"name": "Khloe", "second_name": "Kardashian", "follower_count": 310, "description": "media personality", "country": "United States"},
    {"name": "Justin", "second_name": "Bieber", "follower_count": 295, "description": "pop singer", "country": "Canada"},

    {"name": "Taylor", "second_name": "Swift", "follower_count": 285, "description": "singer songwriter", "country": "United States"},
    {"name": "Kendall", "second_name": "Jenner", "follower_count": 290, "description": "fashion model", "country": "United States"},
    {"name": "Rihanna", "second_name": "Fenty", "follower_count": 270, "description": "singer entrepreneur", "country": "Barbados"},
    {"name": "Neymar", "second_name": "Junior", "follower_count": 220, "description": "footballer", "country": "Brazil"},
    {"name": "Drake", "second_name": "Graham", "follower_count": 145, "description": "rapper producer", "country": "Canada"},
    {"name": "Billie", "second_name": "Eilish", "follower_count": 115, "description": "pop singer", "country": "United States"},
    {"name": "Zendaya", "second_name": "Coleman", "follower_count": 185, "description": "actress model", "country": "United States"},
    {"name": "Shakira", "second_name": "Mebarak", "follower_count": 90, "description": "latin singer", "country": "Colombia"},
    {"name": "Vin", "second_name": "Diesel", "follower_count": 100, "description": "action actor", "country": "United States"},
    {"name": "Leonardo", "second_name": "DiCaprio", "follower_count": 60, "description": "film actor", "country": "United States"},

    {"name": "Kylian", "second_name": "Mbappe", "follower_count": 115, "description": "footballer", "country": "France"},
    {"name": "LeBron", "second_name": "James", "follower_count": 160, "description": "basketball player", "country": "United States"},
    {"name": "Ronaldo", "second_name": "Nazario", "follower_count": 30, "description": "former footballer", "country": "Brazil"},
    {"name": "Katy", "second_name": "Perry", "follower_count": 200, "description": "pop singer", "country": "United States"},
    {"name": "Miley", "second_name": "Cyrus", "follower_count": 215, "description": "singer actress", "country": "United States"},
    {"name": "Bruno", "second_name": "Mars", "follower_count": 145, "description": "pop singer", "country": "United States"},
    {"name": "Marshall", "second_name": "Mathers", "follower_count": 45, "description": "rapper", "country": "United States"},
    {"name": "Post", "second_name": "Malone", "follower_count": 25, "description": "rapper singer", "country": "United States"},
    {"name": "Ed", "second_name": "Sheeran", "follower_count": 50, "description": "pop singer", "country": "United Kingdom"},
    {"name": "Harry", "second_name": "Styles", "follower_count": 50, "description": "pop singer", "country": "United Kingdom"},

    {"name": "Abel", "second_name": "Tesfaye", "follower_count": 70, "description": "rnb singer", "country": "Canada"},
    {"name": "Gigi", "second_name": "Hadid", "follower_count": 75, "description": "fashion model", "country": "United States"},
    {"name": "Zlatan", "second_name": "Ibrahimovic", "follower_count": 65, "description": "footballer", "country": "Sweden"},
    {"name": "Sergio", "second_name": "Ramos", "follower_count": 60, "description": "footballer", "country": "Spain"},
    {"name": "Kevin", "second_name": "Hart", "follower_count": 30, "description": "comedian actor", "country": "United States"},
    {"name": "Will", "second_name": "Smith", "follower_count": 65, "description": "actor producer", "country": "United States"},
    {"name": "Tom", "second_name": "Cruise", "follower_count": 30, "description": "film actor", "country": "United States"},
    {"name": "Chris", "second_name": "Hemsworth", "follower_count": 55, "description": "actor marvel", "country": "Australia"},
    {"name": "Scarlett", "second_name": "Johansson", "follower_count": 35, "description": "actress", "country": "United States"},
    {"name": "Gal", "second_name": "Gadot", "follower_count": 110, "description": "actress model", "country": "Israel"},

    {"name": "Anitta", "second_name": "Larissa", "follower_count": 65, "description": "pop singer", "country": "Brazil"},
    {"name": "Benito", "second_name": "Martinez", "follower_count": 45, "description": "latin rapper", "country": "Puerto Rico"},
    {"name": "Jose", "second_name": "Osorio", "follower_count": 55, "description": "latin singer", "country": "Colombia"},
    {"name": "Karol", "second_name": "Giraldo", "follower_count": 70, "description": "latin singer", "country": "Colombia"},
    {"name": "Doja", "second_name": "Cat", "follower_count": 25, "description": "rapper singer", "country": "United States"},
    {"name": "Nicki", "second_name": "Minaj", "follower_count": 230, "description": "rapper", "country": "Trinidad and Tobago"},
    {"name": "Cardi", "second_name": "B", "follower_count": 170, "description": "rapper", "country": "United States"},
    {"name": "Snoop", "second_name": "Dogg", "follower_count": 80, "description": "rapper", "country": "United States"},
    {"name": "Jay", "second_name": "Z", "follower_count": 20, "description": "rapper mogul", "country": "United States"},
    {"name": "Adele", "second_name": "Adkins", "follower_count": 55, "description": "soul singer", "country": "United Kingdom"},

    {"name": "Roger", "second_name": "Federer", "follower_count": 12, "description": "tennis legend", "country": "Switzerland"},
    {"name": "Rafael", "second_name": "Nadal", "follower_count": 20, "description": "tennis player", "country": "Spain"},
    {"name": "Novak", "second_name": "Djokovic", "follower_count": 15, "description": "tennis player", "country": "Serbia"},
    {"name": "Serena", "second_name": "Williams", "follower_count": 17, "description": "tennis legend", "country": "United States"},
    {"name": "Lewis", "second_name": "Hamilton", "follower_count": 35, "description": "formula driver", "country": "United Kingdom"},
    {"name": "Max", "second_name": "Verstappen", "follower_count": 12, "description": "formula driver", "country": "Netherlands"},
    {"name": "Tiger", "second_name": "Woods", "follower_count": 3, "description": "golf legend", "country": "United States"},
    {"name": "Conor", "second_name": "McGregor", "follower_count": 45, "description": "mma fighter", "country": "Ireland"},
    {"name": "Khabib", "second_name": "Nurmagomedov", "follower_count": 38, "description": "mma fighter", "country": "Russia"},
    {"name": "Usain", "second_name": "Bolt", "follower_count": 11, "description": "sprinter legend", "country": "Jamaica"}
]
